{% set version = '0.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggstance
  version: {{ version|replace("-", "_") }}

source:
  fn: ggstance_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggstance_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggstance/ggstance_{{ version }}.tar.gz
  sha256: 704f7702540a149b352fa5d05dfad62acb5b3b77da6e499ae12d66a55a1fee6c

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-plyr
    - r-rlang
    - r-withr >=2.0.0
  run:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-plyr
    - r-rlang
    - r-withr >=2.0.0

test:
  commands:
    - $R -e "library('ggstance')"           # [not win]
    - "\"%R%\" -e \"library('ggstance')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggstance
  license: GPL-3
  summary: 'A ''ggplot2'' extension that provides flipped components: horizontal versions of
    ''Stats'' and ''Geoms'', and vertical versions of ''Positions''.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
