{% set version = "0.3.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggstance
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggstance_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggstance/ggstance_{{ version }}.tar.gz
  sha256: a112e34873f0606240c81d5111e4ff2d659e39a64f13850290f131016c1b1f2b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=3.2.0
    - r-plyr
    - r-rlang
    - r-withr >=2.0.0
  run:
    - r-base
    - r-ggplot2 >=3.2.0
    - r-plyr
    - r-rlang
    - r-withr >=2.0.0

test:
  commands:
    - $R -e "library('ggstance')"           # [not win]
    - "\"%R%\" -e \"library('ggstance')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggstance
  license: GPL-3
  summary: "A 'ggplot2' extension that provides flipped components: horizontal versions of 'Stats' and 'Geoms', and vertical versions of 'Positions'."
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggstance
# Title: Horizontal 'ggplot2' Components
# Version: 0.3.2
# Authors@R: c( person("Lionel", "Henry", , "lionel@rstudio.com", role = c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("Winston", "Chang", , "winston@rstudio.com", "aut"), person("RStudio", role = "cph") )
# Description: A 'ggplot2' extension that provides flipped components: horizontal versions of 'Stats' and 'Geoms', and vertical versions of 'Positions'.
# Depends: R (>= 3.1.0)
# Imports: ggplot2 (>= 3.2.0), plyr, rlang, withr (>= 2.0.0)
# Suggests: Hmisc, testthat, vdiffr (>= 0.3.0)
# License: GPL-3
# LazyData: true
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Collate: 'flip-aes.R' 'geom-barh.R' 'legend-draw.R' 'geom-boxploth.R' 'geom-colh.R' 'geom-crossbarh.R' 'geom-errorbarh.R' 'geom-histogramh.R' 'geom-linerangeh.R' 'geom-pointrangeh.R' 'geom-violinh.R' 'ggstance.R' 'position-dodgev.R' 'position-dodge2v.R' 'position-jitterdodgev.R' 'position-stackv.R' 'position.R' 'stat-binh.R' 'stat-boxploth.R' 'stat-counth.R' 'stat-summaryh.R' 'stat-xdensity.R'
# NeedsCompilation: no
# Packaged: 2019-06-24 14:45:11 UTC; lionel
# Author: Lionel Henry [aut, cre], Hadley Wickham [aut], Winston Chang [aut], RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-06-24 15:20:03 UTC
