travis:
  secure:
    BINSTAR_TOKEN: BptW2aFxsfhuDP55gSG2OfuWwzKUE3ED8E/osFoPFSGV11z+jm8YTjhHmJz8uKDnB6Ndvqnp6QB+wa3kXR2uWrRX2a+45z3wDqgqQOERvtE+cnRVClpo+FzkZ93oIERSUX/EbfoPN7u/AMj2AidAz45o42yg8y9GaoxiyM1eu7/z1Ggd35NrexNfubeksBbi/FrozxH9spCil3CdyrEFyRY8OQ9ftJlFhoqBQ+oiuPi0I0b7Gc0p6cEN5+Lcn1q3SS/9NgKTJeR+zDFnbropuGghWt4XSmMYzHfN6+3IO3CaCOFC2Jyl5sIbmSkhdsx4ykf71bkYOexmMPIL++al/+Ut6lOK99icpBLrOGlqJUPt8pOcSIuZS9A6T+y50PuoDDBlRsq0OsA0QfJ2mHwoAXYIIZgdvU+b2a42BRieMHlB5hpu5FwD5hlXH4ZBEgGW6GfKvNpH9bra9WSb9mKlGiM6Brhxb8K8ulzFBW4H8TnGPUDGNEjPbYCmlLuaAFm19Lr/+VsTIZR0xOD7ViRsecvn3hjLT72XtXO3QE2Bs5PNA2WcNC0hn2oTYs10z7Hl3Q17sNkK4/CBlMOr/nT1PwoILFewMnyivw6WGvQktq38LjPmItT9/kKCzCWx8Mn3M7DMr9fp3LXTBErMAAVH9wiARlWBc/AO07X9fhZTG3M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
