travis:
  secure:
    BINSTAR_TOKEN: Uhnd0+3Q502aOSECqxYjku3I9yxz1rcbACm6RlHzJaRVxx5K8WL1d8bG5EtGlY63i3AiNTwNkmB5Z/px9VIsE/SCTbushrJ8KlTsccTNvEufYBtIa69IlbD9su26YLMZOYN3SvhDr4SPTQpCvyucMdqpJCWV5ahD+L7Ex2qamkAHSWW143ojLTrUf9Z5RDUEg9CuITJULZE0Y6Nd8jDlkINB50ycEnlv3aAgdEx4H1Xo6kz1LUVHdnMZywgjmjFiG/oqBP8ucUtIWlofaMvm6PFgEojhlc9WqYw2nBgxBOiJuz9pghA267jx8/u7is4ZqurLs5Bg2LoCDgqn6XtJMIrtYd8iJHdvjLbDkt942eci8uUzqllS7uGUVSeFMv/qBIND/U/trvcLZm71iAkl3VQ1TbhphW0gGGDfd4Y0dVwJss07nF/mr+voluvuzQg5IuI9ifr9gDQ23cBhw3hj+1zTIuTKcztEtppuVPoRDVpVxx7ylDjZzOJ0PMNutKNZWjBWP/C+06Q6v91/dinNT1S4lOVk2rnDHpykxjPIkPTyi82pLF2TSkrT/NGHsEn1Ls+QEsB5lJNb+nOio5p0yNUeBcwapscnnUwrZXpeJEActvuwJziXkIdWlaJIJ+mqQEzgaTSvluqOyP27EhvbfPkCRdf2Inni1G3E9VXozKQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
