travis:
  secure:
    BINSTAR_TOKEN: efLmJ2EPDWMTOTAlQSGc+3yS9NlwRDbS3LV3LzPmrcq4mY4MirobkdaL4OEdg84XBYUWZy3ucchy9geVf0oVxR7AeM88CMjAY0JzIY4M+OiOekfWQ78aDi8pnRWEYDBNz7o4tMJzrmFESVGKNMmeMVe19HWnfLL0EA/NFHlimHm8DsXgk3/P4kSRJ/KZtqixWLxwEuhWi4AhbIaDg0Sk20T6PgODdh+h/gUTXJpVdwsD3RfUStyMJmWmsIIFImuQKEGsW7Hsa4KCUQKYAGBtOrD7E3T/F0s2pjeOocGdNTYgUwMsxqzm4yov3t0pPl/V73o1OKlec13TDoKdP1IvMrbWcwb6wa83IZft41D7l14WCtRlN8By2HBE4K59drhuI+DpEOhawnviRDS/ofAG97fJ569O+AHJoUqbXCdJGF09xB/xpWrgK63k66AAYmifX2K7oNXUeIpGfhNaEbs5AhMxnQELYOluFWdqDrlpy3/4HHh1Q3NynIkGg5O5470XqRLRwFFQXsVqqEutzNzgySsaqrvw1Ly50yGE8v4CYL0cH/YS+IG4T8Bubj9ILfjP8TVyl3CzMuqLPZcPsvcK6TQw94Fqh03pKvD7m+hQvLmJ6UxQerp6/1MLTwTp/A30WjmEWHuQqLXk92zDlVq/6zjc3Id01OShBBEEc3emV7U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
