travis:
  secure:
    BINSTAR_TOKEN: cPuY5v8wgCw9lyZ1ds0FfvjGLHR/A0AfNxcXwIKYjhd3QXuvUkgx4Zgp+YCG+2eRmItDFU+L3xUH84hAwjU93MNzRJDnznqIEcwH0J8v85dT2Mtj4YXSy5WxuDsvjJAkinBT3VylA/Fuel1zix7AWH45gHFA0fPljFoO97nCf/ivh3TqAEfzkykxWDeRKp2a1QcmfabfnMccYO0Kvlu1tBcsPjRiOVjTK/WFTRCUzOUCOxDilfUJZ4JS2JnDmVuHxNY8lNhd2UT2anyp7KaJMiRp8lPMsgQhMB5tPmsHRJwBTl5KsoYqx5TT7z3GYzrZxyKCFKBELG/qZjGcyavoAxauGsgSGZX+BnmpuVp6AhZFL9ACqZeOUFy/2/wGmAajPoaRzF2wNywL2bV7TmGIHe0m2PDwRsSvsxiIrMw+65N56e2cc7P1tG8ENaE9W5TN8LjlRNVe54OeIzmX+XWAR5VRXLEduNSeGdHIOZDJpEWUUSo2j1T/3c7gOBpvA3xXQnEK8hvncFZzkzFqfgKhxrkiY93+MuiomRkQkRpF1zUn8+k8eHnyfvbMASiVnY/8AAgkEI4B6LyIu0m0jSNsMxAGf6YsBmcnBvm2Xrz7iH5l88ZxSUD+MGOJ2+gvFgtipt6V9XxE6aMGPFIx4Xw4qQHCv+9T7m4J1VOtzODaqzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
